### ISSUE TITLE
Error while fetching token in Blazor Server App when tried multiple times

### ISSUE THREAD

**Issue by Deepakgullipalli** [Azure-Samples/ms-identity-blazor-server#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I have created a .net 6 blazor server app with ms identity Azure AD B2C with SignUpSignin Userflow which connects to my .net core API in .net 6.
Upon running the solution i'm able to successfully signup and sign in. 
As a user when i close the browser and run the app again. And try to fetch Api data with tokenacquistion "GetAccessTokenForUserAsync" . 
 It throws "No account or login hint was passed to the AcquireTokenSilent call."

### Any log messages given by the failure
> No account or login hint was passed to the AcquireTokenSilent call.

### Expected/desired behavior
> it should fetch the token and I should be able to retrieve the api info

### OS and Version?
> Windows 11

### Versions
> .NET 6 Blazor Server App with Azure AD B2C tenant, SignUpSignIn User flow recommended
.Net Core Web Api in .Net 6

### Mention any other details that might be useful
Upon deleting cache and cookies, and closing all the browser sessions, this works fine for the first time. 
If i close the browser window and run the app again, the issue pops up
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Deepakgullipalli** [comment]
I have followed the below link to resolve this issue

https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access

**Comment by setin1219** [comment]
@Deepakgullipalli , it will be helpful if you can share the code snippet, i am also stuck in same issue
