### ISSUE TITLE
blazorserver-singleOrg sample does not authenticate using AAD app registration

### ISSUE THREAD

**Issue by jladd3** [Azure-Samples/ms-identity-blazor-server#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Configure a valid Domain and TenantId and then enter random string of characters in ClientId and you are still able to authenticate the user. When using a valid ClientId, no app related claims are returned. Specifically, no app role claims are provided.

### Any log messages given by the failure
>

### Expected/desired behavior
> I would expect that with a valid ClientId entered, only user registered for the application in AAD would successfully authenticate. I would also expect to receive app role claims for authorization

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10

### Versions
> .Net Core 3.1

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
Are you sure you're not using User secrets? (in Visual Studio, right click on the project | manage user secrets)

**Comment by jladd3** [comment]
> Are you sure you're not using User secrets? (in Visual Studio, right click on the project | manage user secrets)
I don't have anything in user secrets, but it does seem like appsettings.json is getting cached somewhere. I ran it again after some code changes and the client id was rejected. Perhaps just a VS issue rather than with your code sample.

Should app role claims be available in this sample application is there additional middleware setup required?

**Comment by Shama-K** [comment]
[blazorserver-singleOrg sample](https://github.com/Azure-Samples/ms-identity-blazor-server/tree/main/WebApp-OIDC/MyOrg) is only about authentication with Azure AD. We will provide additional chapters including app roles in near future.
For your question about if app role claims be available, the answer is yes. If you have assigned app roles then it will be present in claims collection. In the sample we are displaying some of the claims, if you want to see all claims then you can update [this line of code](https://github.com/Azure-Samples/ms-identity-blazor-server/blob/5a0d2108d3d1447ed8b3f9522f2382ed918fb490/WebApp-OIDC/MyOrg/blazorserver-singleOrg/Pages/UserClaimsBase.cs#L49).

**Comment by Shama-K** [comment]
Closing the issue, let us know if you need further guidance.
