### ISSUE TITLE
Login to Blazor App goes into a loop when you browse to https://localhost:44365

### ISSUE THREAD

**Issue by mmushatt** [Azure-Samples/ms-identity-blazor-server#6]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [**X**] **documentation issue or request**
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>After I followed the documented steps and browsed to **https://localhost:44365** using the Sign-In policy for my B2C Tenant, the process goes into a loop to the point I never get prompted to authenticate.

### Any log messages given by the failure
>None.  Took a Fiddler trace to determine what was missing to get this resolved

### Expected/desired behavior
>I should be prompted to login via the specified B2C User Flow

### OS and Version?
> Windows 10 version 2004 OS Build 19041.685

### Versions
> Windows 10,  .NET Core 5.0.101

### Mention any other details that might be useful
Found out the process is missing one Redirect URI for the configured AAD Application ( **https://localhost:44365/signin-oidc** ).  After adding this redirect URI, the **WebApp-blazor-server-b2c** Blazor App provided the login page to log into the App.  Thus now I have two Redirect URIs ( https://localhost:44365/authentication/login-callback  and  https://localhost:44365/signin-oidc )
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Shama-K** [comment]
Thanks @mmushatt. Required Redirect URI is: **https://localhost:44365/signin-oidc** and **https://localhost:44365/authentication/login-callback** is not required. [Readme file](https://github.com/Azure-Samples/ms-identity-blazor-server/blob/Shama-K/NewChapter/WebApp-OIDC/B2C/README.md) in [this branch](https://github.com/Azure-Samples/ms-identity-blazor-server/tree/Shama-K/NewChapter) is updated. I'll create a separate Pull Request to close this issue.

**Comment by Shama-K** [comment]
Here is [the Pull Request](https://github.com/Azure-Samples/ms-identity-blazor-server/pull/7).

**Comment by Shama-K** [comment]
Closing this issue for now. Feel free to reopen if there is any issue.

**Comment by InfoZone** [comment]
Hi guys. I'm new here and not sure how to use tags etc, so please be gentle with me :-).
this is happening with me as well after doing the above fix as mentioned.
I'm not sure what else to do?
if i add https://localhost:44365/authentication/login-callback as well in redirect is sort of works but i am not presented with the home page, as i require a user to click on sign in. at the moment the app automatically redirects to the b2b login page before i am able to click on the sign in link. If i remove the above mentioned redirect url, the it goes into an endless loop again

so 2 issues:

1. not presented with home page / sign in option
2. looping still happens 

Thanks
